version: '3.7'

services:
  web:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
    - 80:80
    volumes:
      - ./:/var/www
      - ./vhosts:/etc/nginx/conf.d
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: laravel_app
      args:
        user: forge
        uid: 1000
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    ports:
    - '3306:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'forge:/var/lib/mysql'

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - '6378:6379'
    volumes:
      - 'forge:/data'

volumes:
  forge:
     driver: local