version: '3.7'

services:
  web:
    image: nginx
    container_name: nginx
    ports:
    - 80:80
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: forge
        uid: 1000
    container_name: app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
    - '3307:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'geducarmysql:/var/lib/mysql'

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6378:6379'
    volumes:
      - 'geducarmysql:/data'

volumes:
  geducarmysql:
     driver: local